name: "AWS deploy"

on: 
    push

permissions:
    id-token: write

jobs:
    S3PackageUpload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            
            - name: Setup node.js
              uses: actions/setup-node@v5
              with:
                node-version: '20'
                cache: 'npm'
            
            - name: Install app
              run: npm ci
            
            - name: Build app
              run: npm build
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                role-to-assume: arn:aws:iam::405481637631:role/tane-site-gba
                aws-region: ap-southeast-2
            
            - name: Additional steps
              run: |
                # Your commands that require AWS credentials
                aws sts get-caller-identity
    