name: "AWS deploy"

on: push
    # pull_request:
    #   branches:
    #     - main
    #   types: [closed]

jobs:
    TestBuild:
        # if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            
            - name: Install pnpm
              uses: pnpm/action-setup@v6
              with:
                version: 10
                cache: true
            
            - name: Install app
              run: pnpm install --frozen-lockfile
            
            - name: Test app
              run: pnpm test
    S3BucketWrite:
      needs: TestBuild
      
      env: 
        BUCKET_NAME: "tane.com"
        AWS_REGION: "ap-southeast-2"
      
      permissions:
        id-token: write
      
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v5
            
        - name: Install pnpm
          uses: pnpm/action-setup@v6
          with:
            version: 10
            cache: true

        - name: Install app
          run: pnpm install --frozen-lockfile

        - name: Build app
          run: pnpm build

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6.1.0
          with:
            role-to-assume: arn:aws:iam::405481637631:role/tane-site-gba
            aws-region: ${{ env.AWS_REGION }}
            
        - name: Copy index.html to S3
          run: |
              aws s3 cp ./dist s3://${{ env.BUCKET_NAME }}/ --recursive
        

    